services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: crm-diplom-frontend:local
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - crm-network
    depends_on:
      - database
      - backend

  backend:
    image: php:8.2-apache
    container_name: crm-backend
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: crm_db
      DB_USER: crm_user
      DB_PASSWORD: 123456789
    volumes:
      - ./backend/api:/var/www/html/api
    ports:
      - "8084:80"
    networks:
      - crm-network
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    command: >
      bash -lc "docker-php-ext-install pdo pdo_mysql && apache2-foreground"

  database:
    image: mariadb:10.11
    container_name: crm-database
    environment:
      # Обязательные параметры
      MARIADB_ROOT_PASSWORD: new_password
      MARIADB_DATABASE: crm_db
      MARIADB_USER: crm_user
      MARIADB_PASSWORD: 123456789
      MARIADB_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/sql:/docker-entrypoint-initdb.d:ro
    networks:
      - crm-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: crm-phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: crm_user
      PMA_PASSWORD: 123456789
      UPLOAD_LIMIT: 100M
    ports:
      - "8081:80"
    networks:
      - crm-network
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy 

networks:
  crm-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
